### PR TITLE
Reconfigure linting

### PR DESCRIPTION
**Pull request by rehandalal**
Follows prettier's recommendations:
- to increase the default line length (I chose 99 characters for consistency with Normandy)
- for how to integrate with eslint

I ditched pre-commit for therapist because pre-commit was too slow. Therapist has a lot of optimizations to improve pre-commit linting. This introduces an optional python dev dependency but I think that's okay.

r?

### CODE REVIEW

**Comment by mythmon** [comment]
> Follows prettier's recommendations:
>
> * to increase the default line length (I chose 99 characters for consistency with Normandy)

I agree with the change to 99 characters, but [Prettier's recommendation](https://prettier.io/docs/en/options.html#print-width) is pretty strong to keep the line length at 80 characters, since it will try and cram more into a line that a human might.

**Comment by rehandalal** [comment]
I am bad at reading!

But I think 99chars is still the way to go.

**Comment by rehandalal** [comment]
@magopian 99 characters it what we have normandy set to so I set it to that. I don't know why we didn't go all the way to 100. 

bors r=@magopian

**Comment by mythmon** [comment]
> Not sure about the 99 chars, because why 99

Normandy used 99 chars for JS because we used it for Python. 99 characters come from Python's PEP 8 style guide. For reasons I won't get into, Python prefers having an extra char under the "usual" 80/100 char limits. There isn't a great reason to carry that over to Delivery Console's lints.

**Comment by magopian** [comment]
I just reliased now that
1/ it's missing a README entry or something explaining how to setup therapist (which is a python dependency)
2/ it's basically "breaking git" without prior notice for devs, or explanations on how to fix it (removing the previous `.git/hooks/pre-commit` file)
3/ it's not automatically setting up hooks (it needs `virtualenv venv && source venv/bin/activate && pip install therapist`)
4/ it's not automatically installing the hook (it needs `venv/bin/therapist install`)

I've filed #245

**Pull request merged**
