### PR TITLE
Fix typo for filter object validation message

### PR DESCRIPTION
**Pull request by uhlissuh**
I was looking at Delivery Console today for something and noticed this typo... figured I'd fix it for fun to open my first pull request on another project in our team stack. If this is indeed a typo...

### CODE REVIEW

**Comment by uhlissuh** [comment]
@rehandalal I can't tell if this linting error is related to my tiny lil' change...?

**Comment by rehandalal** [comment]
> @rehandalal I can't tell if this linting error is related to my tiny lil' change...?

It is unrelated and fixed in #1124

**Comment by rehandalal** [comment]
once the other PR merges you should be able to do a "bors r+" here and it will merge this one

**Comment by rehandalal** [comment]
@uhlissuh for future reference PRs should be merged on this project using "bors r+" not the merge button (i've added protections on master so this will not be possible any longer) and you don't need to do a rebase or merge in master unless there are merge conflicts

**Pull request merged**
