### PR TITLE
Eject from Create React App

### LINKED ISSUE #230: Replace moment with date-fns
date-fns is much more performant, and since it's packaged individually you only have to bundle exactly what you're using. 

By the way, in our 1.1M `build/static/js/main.*.js` files 57KB is momentjs. 

The only thing date-fns lacks is namespacing, which is the drawback of importing individual functions. It might not be a problem.

### PR DESCRIPTION
**Pull request by rehandalal**
Fixes #230.

A couple things happening here:
- This was ejected and then common elements from the dev/prod configs were pulled into a base config file. We then use `webpack-merge` to extend the base config and keep things a little more DRY.
- Ditch `react-app-rewired` and work all the overrides into the ejected config files.
- There was some `moment` specific configs and other things that we didn't need in the ejected configs. There are probably some other things we can prune away but I think this is a good start.
- I ditched all the `react-native` stuff because I don't think we care about it.
- We use the `ExtractTextPlugin` on both the dev and prod builds unlike CRA so that we are not inserting inline styles in dev which will help with the CSP implementation I am working on.

As a side note, webpack and some other dependencies are quite outdated here and should be upgraded. Transitioning to webpack 4 is a more involved change and so I will leave that for another PR.

r?

### CODE REVIEW

**Comment by mythmon** [comment]
This works fine for me. I think we could improve the configs a lot, especially removing things that don't make sense for us. I think there is value in merging this now and adjusting other parts of the config more incrementally.

**Comment by rehandalal** [comment]
> I think we could improve the configs a lot, especially removing things that don't make sense for us.

Agreed. I wanted to strip away the obvious (and low hanging) things but there is definitely more work to be done.

I want to upgrade the dependencies too before we start stripping more away.

**Comment by rehandalal** [comment]
Actually it fixes #230 because of https://github.com/mozilla/delivery-console/pull/315/commits/3597f79583bbecbfaa85fd043f2c6d2cc33a17d9. It was not the reason for ejecting, however it is a side effect of optimizing after ejecting.

I haven't confirmed if this fixes #195.

**Comment by rehandalal** [comment]
bors r=@mythmon

**Pull request merged**
