### PR TITLE
extraction of errors causes TypeError

### LINKED ISSUE #543: Error on extension detail page: c is null; can't access its "split" property
https://sentry.prod.mozaws.net/operations/deliveryconsole-stage/issues/4882572/

This is probably a problem somewhere in [v5..v6](https://github.com/mozilla/delivery-console/compare/v5..v6). Prod (v5) works fine and Stage (v6) is broken.

```
TypeError: c is null; can't access its "split" property
```

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #543

I know this change is good because I was able to reproduce it locally and fix. I'm a bit stumped as to why the unit test didn't cover that.

### CODE REVIEW

**Comment by peterbe** [comment]
[That]https://github.com/mozilla/delivery-console/blob/master/src/tests/components/forms/FormItem.test.js#L22() explains why the unit tests didn't notice. Sigh. We need more react-testing-library on these things.

**Comment by mythmon** [comment]
Could the test be improved to use `enzyme#mount` or `enzyme#render` to get a quick set of basic coverage for this? Or would you rather write a robust set of react-testing-library tests for this now?

Either way, I don't want to merge this without tests that would have caught the problem.

**Comment by peterbe** [comment]
I have a test coming.

**Comment by peterbe** [comment]
@mythmon Now, with tests. At least, the test was now failing until I put that fix back in.

**Comment by mythmon** [comment]
bors ping

**Pull request merged**
