### PR TITLE
Show email when logged in, fixes #198

### LINKED ISSUE #198: Show email when logged in
I'm called "Peter Bengtsson" when I use any of my three different email addresses. That's why it's important that it could something like "Peter Bengtsson (pbengtsson@example.com)" or something.

### PR DESCRIPTION
**Pull request by peterbe**
fixes #198

In [the issue](https://github.com/mozilla/delivery-console/issues/198) I made the case that I'm always wonder who I logged in as because my email is different for three different identities where I'm called "Peter Bengtsson". But perhaps it's just me. Either way, I think the change is cheap and it helps a little. 

screen shot 2018-06-20 at 3 31 31 pm

### CODE REVIEW

**Comment by mythmon** [comment]
How about using the name with the email as hover text?

**Comment by rehandalal** [comment]
> How about using the name with the email as hover text?

+1

I was actually just about to suggest that since I think the "which email did I use" problem is a local development issue only.

**Comment by peterbe** [comment]
I'll make it a title hover for the name display.

**Comment by peterbe** [comment]
Updated @rehandalal

**Pull request merged**
