### PR TITLE
Add integrity field to yarn.lock (autogenerated)

### PR DESCRIPTION
**Pull request by mythmon**
This was generated simply by running `yarn`.

### CODE REVIEW

**Comment by mythmon** [comment]
I figured this is going to keep coming up as we keep upgrading. I also expect this is backwards compatible, so it won't affect CI or developers that haven't upgraded yet.

**Comment by mythmon** [comment]
This failed due to the concurrency/memory limitations we saw in #497. @peterbe Any chance you could split that fix out into its own PR?

**Comment by peterbe** [comment]
> Any chance you could split that fix out into its own PR?

https://github.com/mozilla/delivery-console/pull/502

**Comment by peterbe** [comment]
How do you want to play this? 
At the moment, I can't do `yarn add something` or `yarn` because *my* yarn always adds the integrity lines and I don't know how to downgrade my yarn to 1.9.

I can't think of any reason not to land this ASAP. Having said that, I did [land a renovate PR](https://github.com/mozilla/delivery-console/commit/8db5165c37a9aadec95ef7aad79326d03ecde065) minutes ago which might very well either make this PR a git conflict or it's now just outright wrong.

**Comment by mythmon** [comment]
I think we need to just do this all at once. It's going to conflict with any Renovate PR, but Renovate will rebase those just fine. Lets sync up and do this all at once.

**Pull request merged**
