### PR TITLE
Revert "Merge #217"

### LINKED ISSUE #222: Action in recipe listing is missing if the list of actions hasn't been loaded
image

This is likely a result of #217. We should roll that back for now and investigate a better way to load actions.

### PR DESCRIPTION
**Pull request by rehandalal**
This reverts commit 94e1d37f6954890b7701a72eb05fc11e2a0d42a8, reversing
changes made to 635d457661c1ee032872d6da0e581299c4247dce.

Fixes #222.

r?

### CODE REVIEW

**Comment by rehandalal** [comment]
It's just the silly way git's auto generated message is phrased. I think they mean commit 94e1d37 was reverted, returning us to 635d457.

**Comment by rehandalal** [comment]
bors r=@magopian

**Comment by peterbe** [comment]
Sigh. My foray into delivery console isn't great. Why couldn't you just add `<QueryActions/>` to the listing page too?

My original intention was to avoid tech-debt/weirdness (not performance optimization) since soon enough DC isn't just about recipes and then it would be weird that every single page has to load a list of actions, every time.

**Comment by rehandalal** [comment]
> Sigh. My foray into delivery console isn't great. 
Sorry I should have done a deeper dive into this!

So this kind of has to do with how the API returns data. The recipe listing API returns only an action ID. The recipe details API returns the entire action object. Perhaps we should change this on the API end but I think it's overkill. This means on the details page, we don't actually need `<QueryActions />`.

**Comment by peterbe** [comment]
So then I don't get what went wrong. Is it a matter of the order of things? Or race conditions? Like, what went wrong with the recipe listing page? Or rather, why couldn't we just add `<QueryActions/>` to the recipe listing page too as a fail-forward solution?

**Pull request merged**
