### PR TITLE
Cut bors commit messages after "---"

### PR DESCRIPTION
**Pull request by mythmon**

### CODE REVIEW

**Comment by peterbe** [comment]
Heck. I don't know how this works. The commit message doesn't have that stuff. It's the description in the GitHub PR. Right?

If I click to "Edit" a PR, like [this one](https://github.com/mozilla/delivery-console/pull/464) I see a markdown like this:
```
This PR contains the following updates:

| Package | Type | Update | Change | References |
|---|---|---|---|---|
| cssnano | devDependencies | patch | `4.1.0` -> `4.1.3` | [source](https://renovatebot.com/gh/cssnano/cssnano) |

---

### Release Notes

<details>
<summary>cssnano/cssnano</summary>

### [`v4.1.3`](https://renovatebot.com/gh/cssnano/cssnano/releases/v4.1.3)

[Compare Source](https://renovatebot.com/gh/cssnano/cssnano/compare/v4.1.2...v4.1.3)

...
```

So there are actually a bunch of occurrences of the string `---` in there. 5 in a markdown table. The other on its own line. 

How can we know that bors doesn't split it on that first `---` that is part of the markdown table?

**Comment by mythmon** [comment]
Oh, drat. I didn't think about that. I wonder if it would work to make it split on `\n---\n`. Do you think that would good enough, if it worked?

Also, yes, you're right. This is in the PR description, not the commit. I mispoke.

**Comment by mythmon** [comment]
The docs for `cut_body_after` say

> A marker in the PR description that indicates boilerplate that does not belong in the commit message.

In the past this has worked by remove the first instance of the value and all contents after that value from the commit. I think that `\n---\n` will work, and produce few false positives. I hope.

**Comment by mythmon** [comment]
It worked! https://github.com/mozilla/delivery-console/commit/37c96a6f4710afc93c53fc1703150a6d4eaa47ab

**Pull request merged**
